// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuCYmyOUSSlxFFHqRG79WFO7cXCTLVv80',
    appId: '1:976494959751:web:3378b91598743064e9ec22',
    messagingSenderId: '976494959751',
    projectId: 'communityeye-f138d',
    authDomain: 'communityeye-f138d.firebaseapp.com',
    storageBucket: 'communityeye-f138d.firebasestorage.app',
    measurementId: 'G-2R742Q35MY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6mNz9crL41KqwdXDZhIErIaQ7NozikOA',
    appId: '1:976494959751:android:e66bccdb238e7c58e9ec22',
    messagingSenderId: '976494959751',
    projectId: 'communityeye-f138d',
    storageBucket: 'communityeye-f138d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAllqHSLdEQu6RIRKd8vwkph9rHMPqMywI',
    appId: '1:976494959751:ios:71159e244b836d93e9ec22',
    messagingSenderId: '976494959751',
    projectId: 'communityeye-f138d',
    storageBucket: 'communityeye-f138d.firebasestorage.app',
    iosBundleId: 'com.example.communityEye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAllqHSLdEQu6RIRKd8vwkph9rHMPqMywI',
    appId: '1:976494959751:ios:71159e244b836d93e9ec22',
    messagingSenderId: '976494959751',
    projectId: 'communityeye-f138d',
    storageBucket: 'communityeye-f138d.firebasestorage.app',
    iosBundleId: 'com.example.communityEye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuCYmyOUSSlxFFHqRG79WFO7cXCTLVv80',
    appId: '1:976494959751:web:ad39199d8dce22e8e9ec22',
    messagingSenderId: '976494959751',
    projectId: 'communityeye-f138d',
    authDomain: 'communityeye-f138d.firebaseapp.com',
    storageBucket: 'communityeye-f138d.firebasestorage.app',
    measurementId: 'G-S0VZHSZEYH',
  );

}